### ISSUE TITLE
[skiplink] attribute

### ISSUE THREAD

**Issue by thepassle** [thepassle/generic-components#15]
It may make more sense to have skiplink available as an attribute as well, seeing that the component basically only applies some styles.

The same problem as in #13 is true here as well; this would only work if the attribute is used in light dom, not across shadowroots, though arguably here it might be okay because a skiplink should be at the top of the dom.

I imagine it would look something like
```css
a[skiplink] {
  position: absolute;
  left: -999px;
  width: 1px;
  height: 1px;
  top: auto;
}

a[skiplink]:focus {
  top: 0px;
  left: 0px;
  height: auto;
  width: auto;
  margin: auto;
}
```

Usage:

```html
<a href="#main" skiplink>Skip to main content</a>
```

An option here is to ship both a component, and a css 'util' for the time being, although that may be confusing to a user
