### ISSUE TITLE
Internationalized styling

### ISSUE THREAD

**Issue by Malvoz** [thepassle/generic-components#19]
It'd be super cool if internationalized styling was built in, taking this CSS as a random example:

https://github.com/thepassle/generic-components/blob/0f9ca6d9058a8dec9761a3243035fcaba6432e5e/generic-switch/GenericSwitch.js#L46-L48

Using flow-relative properties as defined in [CSS Logical Properties and Values](https://www.w3.org/TR/css-logical-1/) the margin in this example would make sense for `rtl` languages as well:

```CSS
label {
  margin-right: 10px; /* physical property: used as fallback for unsupporting browsers */
  margin-inline-end: 10px; /* logical property: margin-right in latin, margin-left in arabic */
}
```

The physical (non-logical) declarations could be removed once [browser support for Logical Properties](https://caniuse.com/#feat=css-logical-props) is considered good enough.

With this we could add something like "🌎 Internationalization" to the [current list](https://github.com/thepassle/generic-components#generic-components):

> A collection of generic web components with a focus on:
> 
> - 🚹 Accessibility
> - 🏗 Easy to use
> - 🎨 Easy to style

... and "Easy to use" would apply to _everyone_. 🥰
