### ISSUE TITLE
consider [visually-hidden] attribute

### ISSUE THREAD

**Issue by thepassle** [thepassle/generic-components#7]
Rather than shipping a _component_ to mark a node as visually hidden, it might make more sense to support a `visually-hidden` attribute.
Something like:

```html
<p visually-hidden>I am visually hidden!</p>
```

Could be easily achieved by shipping some CSS like:

```css
[visually-hidden] {
  clip: rect(1px, 1px, 1px, 1px);
  clip-path: inset(50%);
  height: 1px;
  width: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
}
```

The benefit of this is that it would only require css, and no javascript. A potential downside of this is how to make this work across shadow roots. 

In apps that dont use shadow dom, this would work perfectly fine, but since global styles dont leak through to shadow roots, that might make things a little awkward for apps that make use of shadow dom, since there's (currently) no way to import css in JS files. 

E.g. you wont be able to do something like:
```js
import visuallyHidden from 'visually-hidden.css';

class MyElement extends HTMLElement {
  constructor() {
    this.attachShadow({mode: 'open'});
    this.shadowRoot.adoptedStyleSheets = [visuallyHidden];
  }
}
```

## skiplinks

This could also create a nice pattern for a skiplink, since you'd be able to do something like:

```html
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/@thepassle/generic-components/visually-hidden.css">
    <style>
      #skiplink:focus {
        /* undo [visually-hidden] styles */
        display: block;
      }
    </style>
  </head>
  <body>
    <a 
      id="skiplink" 
      href="#main"
      visually-hidden
    >
      Skip to main content
    </a>
  </body>
</html>
```

A downside of this is that simply dropping a component in your HTML for this takes some of the headache of manually writing css. Though perhaps there should be a `skiplink` attribute that undoes the visually hidden styles on focus instead?

```html
    <a 
      id="skiplink" 
      href="#main"
      skiplink
    >
      Skip to main content
    </a>
```

Again, this would only work for these attributes being uses in lightdom.

**Comment by jordanaustin** [comment]
For me personally, I wouldn't use a component for visually-hidden, so the idea of pure css makes sense. This is when Lit's `css` tagged template literal is really nice, because you can ship just the css, import it as js an adopt the css into the component. The `<link rel="stylesheet">` isn't a bad compromise I suppose 🤷

**Comment by Malvoz** [comment]
May I suggest considering using [AMP's version of visually-hidden](https://github.com/ampproject/amphtml/blob/c6534d7e16ed95a6dc1386ce7bd8ce9ddc29bdb4/css/ampshared.css#L186-L216) (it is probably the most battle-tested screen reader class out there) as a base for _both_ `[visually-hidden]` and `[skiplink]` since they're fundamentally the same, with the exception that `[skiplink]` is intended to be revealed on focus.

```CSS
[visually-hidden],
[skiplink]:not(:focus) {
  position: fixed !important;
  /* keep it on viewport */
  top: 0px !important;
  left: 0px !important;
  /* give it non-zero size, VoiceOver on Safari requires at least 2 pixels
     before allowing buttons to be activated. */
  width: 4px !important;
  height: 4px !important;
  /* visually hide it with overflow and opacity */
  opacity: 0 !important;
  overflow: hidden !important;
  /* remove any margin or padding */
  border: none !important;
  margin: 0 !important;
  padding: 0 !important;
  /* ensure no other style sets display to none */
  display: block !important;
  visibility: visible !important;
}

/* optional opinionated styles */
[skiplink]:focus {
  position: absolute;
  background-color: #fff;
  padding: .5rem 1rem;
}
```

See this glitch which utilizes both attributes: https://principled-simple-scion.glitch.me/
